# Generated by Django 5.2 on 2025-05-14 16:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=accounts.models.generate_auth_token, editable=False, help_text='System-generated URL-safe auth token.', max_length=43, unique=True)),
                ('email', models.EmailField(help_text='The email address of the user to be created.', max_length=254, unique=True)),
                ('username', models.CharField(default=accounts.models.generate_pronounceable_username, editable=False, help_text='System-generated username, can be edited later.', max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was issued.')),
                ('expires_at', models.DateTimeField(default=accounts.models.default_expiry, help_text='When this token becomes invalid.')),
                ('is_used', models.BooleanField(default=False, help_text='Set to True once the token has been exchanged for a User.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
