# Generated by Django 5.2 on 2025-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationtoken_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
