# Generated by Django 5.2 on 2025-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_has_seen_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
