# Generated by Django 5.2 on 2025-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
