# Generated by Django 5.2 on 2025-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivey', 'Delivey')], default='Pickup', max_length=20),
        ),
    ]
