# Generated by Django 5.2 on 2025-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='schedule_order',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
