# Generated by Django 5.2 on 2025-06-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_schedule_order_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
