# Generated by Django 5.2 on 2025-06-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_fulldateandtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total',
        ),
    ]
