# Generated by Django 5.2 on 2025-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_amount_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivey', 'delivey')], default='pickup', max_length=20),
        ),
    ]
