# Generated by Django 5.2 on 2025-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
