# Generated by Django 5.2 on 2025-06-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_ready_for_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ready_for_pickup',
            new_name='order_completed',
        ),
    ]
