# Generated by Django 5.2 on 2025-06-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_ready_for_pickup_order_order_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('uber', 'Uber Direct'), ('doordash', 'Doordash Drive'), ('manual', 'Manual/Restaurant')], default='uber', max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_lat', models.FloatField()),
                ('delivery_lng', models.FloatField()),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('quote_requested', 'Quote Requested'), ('submitted', 'Submitted'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('quote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('pickup_ready_dt', models.DateTimeField(blank=True, null=True)),
                ('pickup_deadline_dt', models.DateTimeField(blank=True, null=True)),
                ('dropoff_eta', models.DateTimeField(blank=True, null=True)),
                ('dropoff_deadline_dt', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
