# Generated by Django 5.2 on 2025-06-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderdelivery_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('pickup_ready_dt', models.DateTimeField(blank=True, null=True)),
                ('pickup_deadline_dt', models.DateTimeField(blank=True, null=True)),
                ('dropoff_ready_dt', models.DateTimeField(blank=True, null=True)),
                ('dropoff_deadline_dt', models.DateTimeField(blank=True, null=True)),
                ('pickup_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manifest_total_value', models.IntegerField(blank=True, null=True)),
                ('external_store_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('quote_status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uberquote', to='orders.order')),
            ],
        ),
    ]
