# Generated by Django 5.2 on 2025-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delivery_delete_orderdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='vehicle_details',
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], default='pickup', max_length=20),
        ),
        migrations.AlterField(
            model_name='uberquote',
            name='quote_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
